---
name: Pylint
on: [ push ]
jobs:
  formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }} for Pylint
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Pylint
        run: pip install pylint

      - name: Check Score
        run: |
          NEW_SCORE=$(pylint `find . -name "*.py"` | grep 'Your code has been rated' | awk '{print $10}' | awk -F/ '{print $1}')
          OLD_SCORE=$(cat .pylint-score)
          THREESHOLD_SCORE=$OLD_SCORE
          [ "$(echo "$NEW_SCORE > $THREESHOLD_SCORE" | bc)" -eq 1 ] && { echo "THREESHOLD_SCORE=$THREESHOLD_SCORE"; echo "$THREESHOLD_SCORE" > .pylint-score; }
          pylint --fail-under $THREESHOLD_SCORE `find . -name "*.py"`
      - name: Update new score
        if: [$OLD_SCORE -lt $THREESHOLD_SCORE] 
        run: |
          git config --global user.name "BlackBot"
          git config --global author.name "BlackBot"
          git config --global user.email "bodcsoft@bodc.ac.uk"
          git config --global author.email "bodcsoft@bodc.ac.uk"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git checkout $GITHUB_HEAD_REF
          git pull
          git commit -am "Update pylint score"
          git push