---
name: Pylint
on: [ push ]
jobs:
  formatting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }} for Pylint
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Pylint
        run: pip install pylint
      - name: Check Score
        run: |
          NEW_SCORE=$(pylint `find . -name "*.py"` | grep 'Your code has been rated' | awk '{print $10}' | awk -F/ '{print $1}');
          NEW_SCORE=$(echo "scale=2; $NEW_SCORE" | bc)
          echo $NEW_SCORE
          OLD_SCORE=$(cat .pylint-score);
          OLD_SCORE=$(echo "scale=2; $OLD_SCORE" | bc)
          echo $OLD_SCORE
          THREESHOLD_SCORE=$OLD_SCORE;
          echo $THREESHOLD_SCORE
          if [ "$NEW_SCORE" > "$THREESHOLD_SCORE"] ; then
            echo "THREESHOLD_SCORE=$NEW_SCORE"
            echo "$THREESHOLD_SCORE" > .pylint-score
            echo $NEW_SCORE
            echo $GITHUB_HEAD_REF
          fi
          pylint --fail-under $THREESHOLD_SCORE `find . -name "*.py"`;
